name: build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semver version range syntax.
        architecture: 'x64' # (x64 or x86)
    - name: Install Pandoc
      run: |
        mkdir -p /tmp/pandoc
        cd /tmp/pandoc
        python -m pip --no-cache-dir install setuptools wheel
        python -m pip --no-cache-dir install pandocfilters Pygments
        sudo apt install -y texlive texlive-xetex latexmk wget
        wget -q "https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb"
        sudo dpkg -i pandoc-2.7.3-1-amd64.deb
        rm -rf *.deb
    - name: Install Fonts
      run: |
        mkdir -p /tmp/adodefont
        cd /tmp/adodefont
        wget -q -O source-code-pro.zip https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
        unzip -q source-code-pro.zip -d source-code-pro
        mkdir -p ~/.fonts
        cp -v source-code-pro/*/OTF/*.otf ~/.fonts/
        fc-cache -f
        rm -rf source-code-pro{,.zip}
    - name: Generate PDF
      run: |
        mkdir -p ~/.pandoc/templates
        cp pandoc/algo.latex ~/.pandoc/templates/
        sh pandoc/gen.sh
        mkdir /tmp/template
        mv template.pdf /tmp/template/
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Deploy
      run: |
        cp /tmp/template/template.pdf .
        git add template.pdf
        git config --global user.email "bot@fortcoder.io"
        git config --global user.name "fortcoder BOT"
        git commit -m "Auto-generated PDF commit"
        git push
